package com.spacedlearning.app.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF006686)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBDE9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F2A)
val md_theme_light_secondary = Color(0xFF4C616B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCFE6F1)
val md_theme_light_onSecondaryContainer = Color(0xFF071E27)
val md_theme_light_tertiary = Color(0xFF5F5A7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE5DDFF)
val md_theme_light_onTertiaryContainer = Color(0xFF1B1736)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFF)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFBFCFF)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484D)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFF6AD2FF)
val md_theme_light_surfaceTint = Color(0xFF006686)
val md_theme_light_outlineVariant = Color(0xFFC0C7CD)
val md_theme_light_scrim = Color(0xFF000000)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF6AD2FF)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004D65)
val md_theme_dark_onPrimaryContainer = Color(0xFFBDE9FF)
val md_theme_dark_secondary = Color(0xFFB3CAD5)
val md_theme_dark_onSecondary = Color(0xFF1E333D)
val md_theme_dark_secondaryContainer = Color(0xFF354954)
val md_theme_dark_onSecondaryContainer = Color(0xFFCFE6F1)
val md_theme_dark_tertiary = Color(0xFFC9BFE8)
val md_theme_dark_onTertiary = Color(0xFF312C4C)
val md_theme_dark_tertiaryContainer = Color(0xFF474364)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5DDFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E3E5)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE1E3E5)
val md_theme_dark_surfaceVariant = Color(0xFF40484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E5)
val md_theme_dark_inversePrimary = Color(0xFF006686)
val md_theme_dark_surfaceTint = Color(0xFF6AD2FF)
val md_theme_dark_outlineVariant = Color(0xFF40484D)
val md_theme_dark_scrim = Color(0xFF000000)

// Additional colors for the app
val LightBlue50 = Color(0xFFE1F5FE)
val LightBlue100 = Color(0xFFB3E5FC)
val LightBlue200 = Color(0xFF81D4FA)

val Grey50 = Color(0xFFFAFAFA)
val Grey100 = Color(0xFFF5F5F5)
val Grey200 = Color(0xFFEEEEEE)

val Green100 = Color(0xFFCCFF90)
val Green200 = Color(0xFFB2FF59)
val Green300 = Color(0xFF76FF03)

val Orange100 = Color(0xFFFFE0B2)
val Orange200 = Color(0xFFFFCC80)

val Red100 = Color(0xFFFFCCBC)
val Red200 = Color(0xFFFFAB91)